name: build-docker

on:
  push


jobs:

  buildx:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        id: prepare
        run: |
          echo ::set-output name=branch::migrate_to_alpine
          echo ::set-output name=docker_image::ghcr.io/ejsmit/postfix
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: juanluisbaptiste/docker-postfix
          ref: ${{ steps.prepare.outputs.branch }}
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1.4.0
        id: buildx
        with:
          version: latest
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ejsmit
          password: ${{ secrets.CR_PAT }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag "${{ steps.prepare.outputs.docker_image }}:latest" \
            --output "type=image,push=true" .
      - name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery ${{ steps.prepare.outputs.docker_image }}:latest
