name: build-docker

on:
  push


jobs:

  buildx:
    runs-on: ubuntu-latest

    steps:
      - 
        name: Prepare
        id: prepare
        run: |
          echo ::set-output name=branch::migrate_to_alpine
          echo ::set-output name=docker_image::ghcr.io/ejsmit/postfix
      - 
        name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          repository: juanluisbaptiste/docker-postfix
          ref: ${{ steps.prepare.outputs.branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        uses: docker/setup-buildx-action@v1
        id: buildx
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ejsmit
          password: ${{ secrets.CR_PAT }}
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.prepare.outputs.docker_image }}:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}



